InternetProvider/InternetProvider/ViewModels/Home/HomeViewModel.cs
using System.Collections.Generic;
using InternetProvider.BusinessObjects;

namespace InternetProvider.ViewModels
{
    public class HomeViewModel
    {
        public List<News> Newses { get; set; }
        public List<Advantage> Advantages { get; set; }
    }
}

InternetProvider/InternetProvider/Controllers/AdvantageController.cs
using System.Data.Common;
using System.Linq;
using System.Web.Mvc;
using InternetProvider.BusinessObjects;
using InternetProvider.RepositoryImplementation;
using NLog;

namespace InternetProvider.Controllers
{
    [AllowAnonymous]
    public class AdvantageController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly UnitOfWork _unitOfWork;

        public AdvantageController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public ActionResult MoreDetails(int id)
        {
            Logger.Trace("Starting AdvantageController MoreDetails method with parameter id = {0}. Previous page {1}",
                id, Request.UrlReferrer);
            Advantage advantage;
            try
            {
                advantage = _unitOfWork.Advantage.GetAll().First(x => x.Id == id);
                Logger.Trace("Search Advantage to display with the search criteria id={0}", id);
            }
            catch (DbException ex)
            {
                Logger.Error("Advantage {0} Not found", id);
                ModelState.AddModelError("User", ex.Message);
                return View("~/Views/Error/ErrorPage.cshtml",
                    new HandleErrorInfo(ex, ControllerContext.RouteData.Values["controller"].ToString(),
                        ControllerContext.RouteData.Values["action"].ToString()));
            }

            return PartialView("_FullTextAdvantage", advantage);
        }
    }
}

InternetProvider/InternetProvider/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using InternetProvider.BusinessLogic;
using InternetProvider.RepositoryImplementation;
using InternetProvider.ViewModels;
using NLog;

namespace InternetProvider.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly UnitOfWork _unitOfWork;

        public HomeController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index()
        {
            Logger.Trace("Starting HomeController Index method. Previous page : {0}", Request.UrlReferrer);
            var newsService = new NewsService();
            var advantageService = new AdvantageService();
            Logger.Trace("Creating services {0} , {1}", newsService, advantageService);
            var model = new HomeViewModel
            {
                Newses = newsService.CutText(_unitOfWork.News.OrderByDescendingPublicationDate().ToList()),
                Advantages = AdvantageService.CutText(_unitOfWork.Advantage.GetAll().ToList())
            };
            return View(model);
        }
    }
}

InternetProvider/InternetProvider/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using InternetProvider.BusinessLogic;
using InternetProvider.BusinessObjects;
using InternetProvider.Models;
using InternetProvider.RepositoryImplementation;
using InternetProvider.ViewModels;
using NLog;

namespace InternetProvider.Controllers
{
    public class NewsController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly List<News> _newsList;
        private readonly UnitOfWork _unitOfWork;

        public NewsController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _newsList = _unitOfWork.News.OrderByDescendingPublicationDateGetAll().ToList();
        }

        [HttpGet]
        public ViewResult MoreDetails(int id)
        {
            Logger.Trace("Starting NewsController MoreDetails method with parameter id = {0}. Previous page {1}", id,
                Request.UrlReferrer);
            var model = new NewsCommentsViewModel();
            Logger.Trace("Searching news with parameter id={0}", id);
            var news = _unitOfWork.News.GetAll().First(x => x.Id == id);
            model.Author = news.Author;
            model.PublicationDate = news.PublicationDate;
            model.Text = news.Text;
            model.Title = news.Title;
            model.Picture = news.Picture.ToList();
            model.Time = DateTime.Now;
            model.Comments = _unitOfWork.Comment.CommentsByNews(id).ToList();
            model.Id = news.Id;

            if (User.Identity.IsAuthenticated)
                model.AuthorName = User.Identity.Name;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(NewsCommentsViewModel model)
        {
            Logger.Trace("Starting NewsController PostComment method. Previous page {0}", Request.UrlReferrer);

            if (ModelState.IsValid)
            {
                var comment = new Comment
                {
                    AuthorName = model.AuthorName,
                    Time = model.Time,
                    UserComm = model.UserComm,
                    NewsId = model.Id
                };
                try
                {
                    Logger.Info("Comment with id={0} entry in the database", comment.Id);
                    _unitOfWork.Comment.Create(comment);
                    _unitOfWork.Save();
                }
                catch (DbUpdateException ex)
                {
                    Logger.Error("DbUpdateException {0} ", ex.Message);
                    return View("~/Views/Error/ErrorPage.cshtml",
                        new HandleErrorInfo(ex, ControllerContext.RouteData.Values["controller"].ToString(),
                            ControllerContext.RouteData.Values["action"].ToString()));
                }
                Logger.Info("User {0} has created a new comment", model.AuthorName);
                return RedirectToAction("MoreDetails", new {id = model.Id});
            }
            Logger.Info("New comment by author {0} was not created", model.AuthorName);
            return RedirectToAction("MoreDetails", new {id = model.Id});
        }

        public ViewResult GetAllNews(int page = 1)
        {
            Logger.Trace("Starting NewsController GetAllNews method with parameter page={0}. Previous page {1}", page,
                Request.UrlReferrer);
            var pageSize = 3;
            var newsService = new NewsService();
            var newslist = newsService.CutText(_newsList.Skip((page - 1)*pageSize).Take(pageSize).ToList());

            var pageInfo = new PageInfo {PageNumber = page, PageSize = pageSize, TotalItems = _newsList.Count};
            var model = new NewsPagesViewModel
            {
                Newses = newslist,
                PageInfo = pageInfo
            };
            return View(model);
        }
    }
}

InternetProvider/InternetProvider/Views/Home/Index.cshtml
@model InternetProvider.ViewModels.HomeViewModel

<div id="content" class="container">
    <div class="row margin-top-30">
        <div class="col-md-12 text-center">
            <h2 class="text-center">Connect to us and receive a bonus.</h2>
            <p class="text-center capt">ApexHome delivers Ukraine`s FASTEST INTERNET, according to speedtest.net</p>
        </div>
    </div>
    <div class="row margin-top-10">
        <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="active item">
                    <img src="/Images/slideshow/slide1.jpg" alt=""/>
                </div>
                <div class="item">
                    <img src="/Images/slideshow/slide2.jpg" alt=""/>
                </div>
                <div class="item">
                    <img src="/Images/slideshow/slide3.jpg" alt=""/>
                </div>
                <div class="item">
                    <img src="/Images/slideshow/slide4.jpg" alt=""/>
                    <h2>Slide 4</h2>
                </div>
            </div>
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <div class="container">
        <div class="post">
            <i class="fa fa-graduation-cap fa-4x" aria-hidden="true"></i>
            <h2> Experience</h2>
            <p> Company ApexHome - a diversified telecommunications company. We present the entire range of solutions for private and public organizations, large corporations. Work experience and impeccable reputation allows us to provide our customers with reliable, high-quality access to the Internet.</p>
        </div>
        <div class="post">
            <i class="fa fa-users fa-4x" aria-hidden="true"></i>
            <h2> Partners</h2>
            <p> ApexHome included in the Ukrainian traffic exchange network UA-IX at 80 Gbit / s. We built Hitkalelut with all the leading operators in Ukraine, to efficiently manage data transfer routes between networks. Our partners: Ukrtelecom,Trinity,Matrix,Volia, Giganet,Telenex and others.</p>
        </div>
        <div class="post">
            <i class="fa fa-laptop fa-4x" aria-hidden="true"></i>
            <h2> New technologies</h2>
            <p> Our network is based on the newest equipment using 2016 technology. We managed to achieve a combination of high quality and low prices. We use the latest digital technology, the latest telecommunication equipment and software. We use cloud technologies and Big Data.</p>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document)
            .ready(function() {
                jQuery('.post')
                    .addClass("hidd")
                    .viewportChecker({
                        classToAdd: 'visibl animated fadeInUp',
                        offset: 100
                    });
            });
    </script>
</div>
<div class="section-heading">
    <h2>News</h2>
    <div class="line"></div>
</div>
<div class="container">
    <div class="row">
        <section id="homeBLog" class="demo-1">
            <div class="grid">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="homBlog-area">
                            <div class="homeBlog-content">
                                <div class="row">
                                    @foreach (var item in Model.Newses)
                                    {
                                        <div class="col-lg-4 col-md-4 col-sm-4">
                                            <div class="single-Blog">
                                                <div class="single-blog-left">
                                                    <ul class="blog-comments-box">
                                                        <li>
                                                            @item.PublicationDate.ToString("MMMM")
                                                            <h2>@item.PublicationDate.Day</h2>@item.PublicationDate.Year
                                                        </li>
                                                        <li>
                                                            <a href="#">
                                                                <span class="fa fa-comments"></span>@item.Comments.Count
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="single-blog-right">
                                                    <div class="blog-img">
                                                        <figure class="blog-figure">
                                                            <a href="@Url.Action("MoreDetails", "News", new {item.Id})">
                                                                @foreach (var item2 in item.Picture)
                                                                {
                                                                    <img src="@Url.Content(item2.PicturePath)" alt="img">
                                                                }
                                                            </a>
                                                            <span class="image-effect"></span>
                                                        </figure>
                                                    </div>

                                                    <div class="blog-content">
                                                        <h2>@item.Title</h2>
                                                        <p>@item.Text...</p>
                                                        <div class="readmore_area">
                                                            @Html.ActionLink("Read More", "MoreDetails", "News", new {id = item.Id}, new {target = "_self", @class = "btn btn-aqua"})
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    <a href="@Url.Action("GetAllNews", "News")" class=" btn-buy">News Archive</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

<div class="section-heading">
    <h2>Our advantages</h2>
    <div class="line"></div>
</div>
<div class="blockwidth">
    <div class="container">
        <div class="row">
            @for (var i = 0; i < 3; i++)
            {
                <div class="portfolio-item col-sm-4 animate fadeIn">
                    <div class="image-hover">
                        <figure>
                            @foreach (var item in Model.Advantages[i].Picture)
                            {
                                <img src="@Url.Content(item.PicturePath)" alt="image1">
                            }

                            <div class="overlay">
                                <a class="expand" href="#">Image Link</a>
                            </div>
                        </figure>
                        <h3 class="margin-top-20">@Model.Advantages[i].Name</h3>
                        <p class="margin-top-10 margin-bottom-20">@Model.Advantages[i].Text...</p>
                        <div class="btn btn-default">
                            @Html.ActionLink("Read More", "MoreDetails", "Advantage", new {id = Model.Advantages[i].Id}, new {target = "_self", @class = "btn btn-aqua"})
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="section-heading">
    <h2>Security and Speed</h2>
    <div class="line"></div>
</div>
<div class="container">
    <div class="specialshare">
        <div class="row">

            @for (var i = 3; i < Model.Advantages.Count; i++)
            {
                <div class="view view-first">
                    @foreach (var item in Model.Advantages[i].Picture)
                    {
                        <img src="@Url.Content(item.PicturePath)" alt="image1">
                    }
                    <div class="mask">
                        <h2>@Model.Advantages[i].Name</h2>
                        <p>@Model.Advantages[i].Text</p>
                        @Html.ActionLink("Read More", "MoreDetails", "Advantage", new {id = Model.Advantages[i].Id}, new {target = "_self", @class = "btn btn-aqua"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>