InternetProvider/InternetProvider/Controllers/MapController.cs
using System.Web.Mvc;
using InternetProvider.RepositoryImplementation;
using NLog;

namespace InternetProvider.Controllers
{
    [AllowAnonymous]
    public class MapController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly UnitOfWork _unitOfWork;

        public MapController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index()
        {
            Logger.Trace("Starting MapController Index method. Previous page {0}", Request.UrlReferrer);
            return View();
        }

        public JsonResult GetData()
        {
            var markers = _unitOfWork.Map.GetAll();
            return Json(markers, JsonRequestBehavior.AllowGet);
        }
    }
}

InternetProvider/InternetProvider/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using InternetProvider.BusinessLogic;
using InternetProvider.BusinessObjects;
using InternetProvider.Models;
using InternetProvider.RepositoryImplementation;
using InternetProvider.ViewModels;
using NLog;

namespace InternetProvider.Controllers
{
    public class NewsController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly List<News> _newsList;
        private readonly UnitOfWork _unitOfWork;

        public NewsController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _newsList = _unitOfWork.News.OrderByDescendingPublicationDateGetAll().ToList();
        }

        [HttpGet]
        public ViewResult MoreDetails(int id)
        {
            Logger.Trace("Starting NewsController MoreDetails method with parameter id = {0}. Previous page {1}", id,
                Request.UrlReferrer);
            var model = new NewsCommentsViewModel();
            Logger.Trace("Searching news with parameter id={0}", id);
            var news = _unitOfWork.News.GetAll().First(x => x.Id == id);
            model.Author = news.Author;
            model.PublicationDate = news.PublicationDate;
            model.Text = news.Text;
            model.Title = news.Title;
            model.Picture = news.Picture.ToList();
            model.Time = DateTime.Now;
            model.Comments = _unitOfWork.Comment.CommentsByNews(id).ToList();
            model.Id = news.Id;

            if (User.Identity.IsAuthenticated)
                model.AuthorName = User.Identity.Name;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(NewsCommentsViewModel model)
        {
            Logger.Trace("Starting NewsController PostComment method. Previous page {0}", Request.UrlReferrer);

            if (ModelState.IsValid)
            {
                var comment = new Comment
                {
                    AuthorName = model.AuthorName,
                    Time = model.Time,
                    UserComm = model.UserComm,
                    NewsId = model.Id
                };
                try
                {
                    Logger.Info("Comment with id={0} entry in the database", comment.Id);
                    _unitOfWork.Comment.Create(comment);
                    _unitOfWork.Save();
                }
                catch (DbUpdateException ex)
                {
                    Logger.Error("DbUpdateException {0} ", ex.Message);
                    return View("~/Views/Error/ErrorPage.cshtml",
                        new HandleErrorInfo(ex, ControllerContext.RouteData.Values["controller"].ToString(),
                            ControllerContext.RouteData.Values["action"].ToString()));
                }
                Logger.Info("User {0} has created a new comment", model.AuthorName);
                return RedirectToAction("MoreDetails", new {id = model.Id});
            }
            Logger.Info("New comment by author {0} was not created", model.AuthorName);
            return RedirectToAction("MoreDetails", new {id = model.Id});
        }

        public ViewResult GetAllNews(int page = 1)
        {
            Logger.Trace("Starting NewsController GetAllNews method with parameter page={0}. Previous page {1}", page,
                Request.UrlReferrer);
            var pageSize = 3;
            var newsService = new NewsService();
            var newslist = newsService.CutText(_newsList.Skip((page - 1)*pageSize).Take(pageSize).ToList());

            var pageInfo = new PageInfo {PageNumber = page, PageSize = pageSize, TotalItems = _newsList.Count};
            var model = new NewsPagesViewModel
            {
                Newses = newslist,
                PageInfo = pageInfo
            };
            return View(model);
        }
    }
}

InternetProvider/InternetProvider/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Web.Mvc;
using InternetProvider.BusinessObjects;
using InternetProvider.RepositoryImplementation;
using InternetProvider.ViewModels;
using InternetProvider.ViewModels.Payment;
using NLog;

namespace InternetProvider.Controllers
{
    [AllowAnonymous]
    public class PaymentController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly UnitOfWork _unitOfWork;

        public PaymentController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index()
        {
            Logger.Trace("Starting the PaymentController Index method. Previous page {0}", Request.UrlReferrer);
            var model = new PaymentViewModel {Date = DateTime.Now};

            var types = new List<Currency>();
            types.Add(new Currency { Value = 1, Text = "GRN" });
            types.Add(new Currency { Value = 25, Text = "Dollar" });
            types.Add(new Currency { Value = 28, Text = "Evro" });
            ViewBag.PartialTypes = types;

            if (User.Identity.IsAuthenticated)
            {
                var user = _unitOfWork.User.Find(User.Identity.Name);
                model.AccountId = user.Id;
                Logger.Trace("User authentication {0}", User.Identity.Name);
            }
            ViewBag.Message = TempData["message"] as string;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Success(PaymentViewModel model)
        {
            Logger.Trace("Starting the PaymentController Success Method. Previous page {0}", Request.UrlReferrer);
            if (ModelState.IsValid)
            {
                var payment = new Payment
                {
                    AccountId = model.AccountId,
                    Date = model.Date,
                    Sum = model.Sum
                };
                Logger.Info("Creating new payment AccountNumber ={0} , Money ={1}", model.AccountId, model.Sum);
                try
                {
                    _unitOfWork.Payment.Create(payment);
                    _unitOfWork.Save();
                }
                catch (DbUpdateException ex)
                {
                    Logger.Error("DbUpdateException {0}", ex.Message);
                    TempData["message"] = "This account does not exist";
                    return RedirectToAction("Index");
                }

                var user = _unitOfWork.User.Get(model.AccountId);
                user.Account.Money += model.Sum;

                _unitOfWork.Save();
                Logger.Info("User successfully added money to Account {0}", model.AccountId);
                TempData["message"] = "The account is successfully recharged";
                return RedirectToAction("Index");
            }
            Logger.Info("Recharge accountNumber {0} has failed", model.AccountId);
            return View("Index", model);
        }
    }
}

InternetProvider/InternetProvider/Controllers/RatesController.cs
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using InternetProvider.RepositoryImplementation;
using InternetProvider.ViewModels;
using NLog;

namespace InternetProvider.Controllers
{
    [AllowAnonymous]
    public class RatesController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly UnitOfWork _unitOfWork;

        public RatesController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ViewResult Index(int id)
        {
            Logger.Trace("Starting RateController Index method with parameter id = {0}. Previous page {1}", id,
                Request.UrlReferrer);
            var service = _unitOfWork.Service.Get(id);
            Logger.Trace("Searching Service with parameter id={0} and get all its rates", id);
            var model = new RateListViewModel
            {
                Rates = service.Rates.ToList(),
                ServiceId = service.Rates.Select(x => x.Service.Id).First(),
                ServiceName = service.Name
            };
            return View(model);
        }

        public ActionResult Details(int id)
        {
            Logger.Trace("Starting RateController Details method with the parameter id = {0}. Previous page {1}", id,
                Request.UrlReferrer);
            if (User.Identity.IsAuthenticated)
            {
                var user = _unitOfWork.User.Find(User.Identity.Name);

                var rate = _unitOfWork.Rate.Get(id);

                if (user.Account.Rates.Contains(_unitOfWork.Rate.Get(id)))
                {
                    Logger.Info("User {0} attempted to re-connect rate {1}", user.Email, rate.Name);
                    return Content("You have already connected  to this rate");
                }
                if (user.Account.Rates.Any(item => item.ServiceId == rate.ServiceId))
                {
                    Logger.Info(
                        "User {0} attempted to connect rate {1}, but he is already connected to One of the rates of the service ServiceId={2}",
                        user.Email, rate.Name, rate.ServiceId);
                    return Content("You have already connected to one of the rates for this service");
                }
                user.Account.Rates.Add(_unitOfWork.Rate.Get(id));
                try
                {
                    _unitOfWork.Save();
                }
                catch (DbUpdateException ex)
                {
                    Logger.Error("DbUpdateException {0}", ex.Message);
                    return View("~/Views/Error/ErrorPage.cshtml",
                        new HandleErrorInfo(ex, ControllerContext.RouteData.Values["controller"].ToString(),
                            ControllerContext.RouteData.Values["action"].ToString()));
                }

                Logger.Info("User {0} successfully connect rate {1}", user.Email, rate.Name);
                return Content("The data has been successfully added to the personal cabinet");
            }
            Logger.Info("The user tried to connect the rate, but it was not logged in the system");
            return Content("Please, login to your personal account or register");
        }

        public ViewResult SortByPriceDes(int id)
        {
            Logger.Trace("Starting RateController SortByPriceDes method with parameter id = {0}. Previous page {1}",
                id, Request.UrlReferrer);
            var rates = _unitOfWork.Rate.SortByPriceDes(id).ToList();
            var service = _unitOfWork.Service.Get(id);
            var model = new RateListViewModel
            {
                Rates = rates,
                ServiceId = id,
                ServiceName = service.Name
            };
            return View("Index", model);
        }

        public ViewResult SortByPriceInc(int id)
        {
            Logger.Trace("Starting RateController SortByPriceInc method with parameter id = {0}. Previous page {1}",
                id, Request.UrlReferrer);
            var rates = _unitOfWork.Rate.SortByPriceInc(id).ToList();
            var service = _unitOfWork.Service.Get(id);
            var model = new RateListViewModel
            {
                Rates = rates,
                ServiceId = id,
                ServiceName = service.Name
            };
            return View("Index", model);
        }

        public ViewResult SortByAlph(int id)
        {
            Logger.Trace("Starting RateController SortByAlph method with parameter id = {0}. Previous page {1}",
                id, Request.UrlReferrer);
            var rates = _unitOfWork.Rate.SortByAlph(id).ToList();
            var service = _unitOfWork.Service.Get(id);
            var model = new RateListViewModel
            {
                Rates = rates,
                ServiceId = id,
                ServiceName = service.Name
            };
            return View("Index", model);
        }

        public ViewResult SortByAlphDec(int id)
        {
            Logger.Trace("Starting RateController SortByAlphDec method with parameter id = {0}. Previous page {1}",
                id, Request.UrlReferrer);
            var rates = _unitOfWork.Rate.SortByAlphDec(id).ToList();
            var service = _unitOfWork.Service.Get(id);
            var model = new RateListViewModel
            {
                Rates = rates,
                ServiceId = id,
                ServiceName = service.Name
            };
            return View("Index", model);
        }

        public FileResult DownloadPdf(int id)
        {
            Logger.Trace("Starting RateController DownloadPdf method with parameter id = {0}. Previous {1}",
                id, Request.UrlReferrer);
            Logger.Trace("There is a file download with id = {0}", id);
            var rate = _unitOfWork.Rate.Get(id);
            var path = "~/Content/RatesFiles/" + rate.File.Name;
            return File(path, "application/pdf", rate.File.Name);
        }
    }
}

InternetProvider/InternetProvider/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <title>InternetProvider</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/site.css")
    @Scripts.Render("~/scripts/jquery-3.1.0.min.js")
    @Scripts.Render("~/scripts/bootstrap.js")
    @Scripts.Render("~/scripts/jquery-ui-1.12.0.js")
    @Styles.Render("~/Content/themes/base/jquery-ui.css")
    @Scripts.Render("~/Scripts/datepicker.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.js")
    <link rel="stylesheet" type="text/css" href="/Content/animate.css"/>
    <script src="/Scripts/jquery.viewportchecker.min.js"></script>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Habibi" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Cinzel+Decorative:900" rel="stylesheet" type="text/css">
    <link href="/Content/font-awesome.css" rel="stylesheet">
    <script type="text/javascript" language="javascript">
        $.validator.unobtrusive.adapters.addBool("mandatory", "required");
    </script>
    <script type="text/javascript">
        $(document)
            .ready(function() {

                $(window)
                    .scroll(function() {
                        if ($(this).scrollTop() > 100) {
                            $('.scrollup').fadeIn();
                        } else {
                            $('.scrollup').fadeOut();
                        }
                    });

                $('.scrollup')
                    .click(function() {
                        $("html, body").animate({ scrollTop: 0 }, 600);
                        return false;
                    });

            });
    </script>
</head>
<body>

<div id="header" class="container">
    <div class="row">
        <div class="logo">
            <a href="/" title="">
                <h2>ApexHome</h2>
            </a>
        </div>
        @Html.Partial("_LoginPartial")
        <div class="col-md-12">
            <img src="~/Images/phone3.png"/>
        </div>
        <div class="clear"></div>
        <nav id="nav" role="navigation">
            <a href="#nav" title="Show navigation">Show navigation</a> <a href="#" title="Hide navigation">Hide navigation</a>
            <ul class="clearfix">
                <li>
                    <a href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li>
                    <a href="">
                        <span>Rates</span></a>
                    <ul>
                        @{
                            Html.RenderAction("Index", "ServicesMenu");
                        }
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Map")">Coverage</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "AdditionalServices")">Services</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "ContactInformation")">Contact</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Payment")">Payment</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
<div>
    @RenderBody()
    <a href="#" class="scrollup"></a>
</div>
<footer class="footer-distributed">
    <div class="footer-left">
        <p class="footer-links">
            <a href="@Url.Action("Index", "Home")">Home</a>
            ·
            <a href="@Url.Action("Index", "Services")">Services</a>
            ·
            <a href="@Url.Action("Index", "News")">News</a>
            ·
            <a href="@Url.Action("Index", "ContactInformation")">Contact</a>
            ·
            <a href="@Url.Action("Index", "Rates", new {Id = 1})">Rates</a>
            ·
            <a href="@Url.Action("Index", "Coverage")">Coverage</a>
            ·
            <a href="@Url.Action("Index", "Rates", new {Id = 1})">Internet</a>
            ·
            <a href="@Url.Action("Index", "Rates", new {Id = 2})">Phone</a>
            ·
            <a href="@Url.Action("Index", "Rates", new {Id = 4})">IPTV</a>
            ·
            <a href="@Url.Action("Index", "Rates", new {Id = 3})">KTV</a>
        </p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p>
                <span>80 Revolution Street</span> Kharkiv, Ukraine
            </p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+38 050 9837001</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p>
                <a href="mailto:apexHome@gmail.com">ApexHome@gmail.com</a>
            </p>
        </div>
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            ApexHome - The largest Internet provider northeastern Ukraine. One of the largest suppliers of online resources in Europe.
        </p>
    </div>
</footer>
<div id="footer">
    <div class="container">
        <div class="row">
            <div id="copyright" class="col-md-12">
                <p>Copyright 2016 ApexHome. All rights reserved.</p>
            </div>
        </div>
    </div>
</div>
</body>
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/Scripts/AgreeScript.js")
@RenderSection("scripts", false)
</html>