Blog/Blog/Controllers/ShowPostsController.cs
using System.Web.Mvc;
using Blog.ViewModel;

namespace Blog.Controllers
{
    public class ShowPostsController : Controller
    {
        private readonly Repository.Repository _db = new Repository.Repository();
        private readonly PostsViewModel _model = new PostsViewModel();

        public ActionResult UserPosts(string name)
        {
            _model.Posts = _db.GetUserPosts(name);
            return View("ShowAll", _model);
        }

        public ActionResult GroupPosts(string title)
        {
            _model.Posts = _db.GetPostsFromGroup(title);
            return View("ShowAll", _model);
        }

        public ActionResult PostsTags(int tagId)
        {
            _model.Posts = _db.GetPostsTags(tagId);
            return View("ShowAll", _model);
        }

        public ViewResult ShowAll(PostsViewModel model)
        {
            return View(model);
        }
    }
}

Blog/Blog/Views/ShowPosts/ShowAll.cshtml
@model Blog.ViewModel.PostsViewModel
@{
    ViewBag.Title = "HomePage";
}

@foreach (var item in Model.Posts)
{
    <article class="clearfix">
        <a>
            <img src="data:image;base64,@Convert.ToBase64String(item.Photo)" alt="Post" class="align-left">
        </a>
        <h4 class="title-bg">
            <a href="#">@item.Title</a>
        </h4>
        <p>@item.Text</p>
        <div class="post-summary-footer">
            <ul class="post-data-3">
                <li>
                    <i class="icon-calendar"></i> @item.PostDate
                </li>
                <li>
                    <i class="icon-user"></i> @Html.ActionLink(item.Creator, "UserPosts", "ShowPosts", new {name = item.Creator}, null)
                </li>
                <li>
                    <i class="icon-comment"></i> <a href="#">@item.NumberComments Comments</a>
                </li>
                <li>
                    <i class="icon-tags"></i> <span>@item.PostGroup.Title</span>
                </li>
            </ul>
        </div>
    </article>
}